export const ALL_ANNOUNCEMENTS_REQUEST = "ALL_ANNOUNCEMENTS_REQUEST"
export const ALL_ANNOUNCEMENTS_SUCCESS = "ALL_ANNOUNCEMENTS_SUCCESS"
export const ALL_ANNOUNCEMENTS_FAIL = "ALL_ANNOUNCEMENTS_FAIL"

export const MY_ANNOUNCEMENTS_REQUEST = "MY_ANNOUNCEMENTS_REQUEST"
export const MY_ANNOUNCEMENTS_SUCCESS = "MY_ANNOUNCEMENTS_SUCCESS"
export const MY_ANNOUNCEMENTS_FAIL = "MY_ANNOUNCEMENTS_FAIL"

export const ANNOUNCEMENT_DETAILS_REQUEST = "ANNOUNCEMENT_DETAILS_REQUEST"
export const ANNOUNCEMENT_DETAILS_SUCCESS = "ANNOUNCEMENT_DETAILS_SUCCESS"
export const ANNOUNCEMENT_DETAILS_FAIL = "ANNOUNCEMENT_DETAILS_FAIL"
export const ANNOUNCEMENT_DETAILS_RESET = "ANNOUNCEMENT_DETAILS_RESET"

export const ANNOUNCEMENT_TYPE_REQUEST = "ANNOUNCEMENT_TYPE_REQUEST"
export const ANNOUNCEMENT_TYPE_SUCCESS = "ANNOUNCEMENT_TYPE_SUCCESS"
export const ANNOUNCEMENT_TYPE_FAIL = "ANNOUNCEMENT_TYPE_FAIL"

export const ALL_ADMIN_ANNOUNCEMENTS_REQUEST = "ALL_ADMIN_ANNOUNCEMENTS_REQUEST"
export const ALL_ADMIN_ANNOUNCEMENTS_SUCCESS = "ALL_ADMIN_ANNOUNCEMENTS_SUCCESS"
export const ALL_ADMIN_ANNOUNCEMENTS_FAIL = "ALL_ADMIN_ANNOUNCEMENTS_FAIL"

export const ALL_ARCHIVED_ANNOUNCEMENTS_REQUEST = "ALL_ARCHIVED_ANNOUNCEMENTS_REQUEST"
export const ALL_ARCHIVED_ANNOUNCEMENTS_SUCCESS = "ALL_ARCHIVED_ANNOUNCEMENTS_SUCCESS"
export const ALL_ARCHIVED_ANNOUNCEMENTS_FAIL = "ALL_ARCHIVED_ANNOUNCEMENTS_FAIL"

export const NEW_ANNOUNCEMENT_REQUEST = "NEW_ANNOUNCEMENT_REQUEST"
export const NEW_ANNOUNCEMENT_SUCCESS = "NEW_ANNOUNCEMENT_SUCCESS"
export const NEW_ANNOUNCEMENT_FAIL = "NEW_ANNOUNCEMENT_FAIL"
export const NEW_ANNOUNCEMENT_RESET = "NEW_ANNOUNCEMENT_RESET"

export const ARCHIVE_ANNOUNCEMENT_REQUEST = "ARCHIVE_ANNOUNCEMENT_REQUEST"
export const ARCHIVE_ANNOUNCEMENT_SUCCESS = "ARCHIVE_ANNOUNCEMENT_SUCCESS"
export const ARCHIVE_ANNOUNCEMENT_FAIL = "ARCHIVE_ANNOUNCEMENT_FAIL"
export const ARCHIVE_ANNOUNCEMENT_RESET = "ARCHIVE_ANNOUNCEMENT_RESET"

export const UPDATE_ANNOUNCEMENT_REQUEST = "UPDATE_ANNOUNCEMENT_REQUEST"
export const UPDATE_ANNOUNCEMENT_SUCCESS = "UPDATE_ANNOUNCEMENT_SUCCESS"
export const UPDATE_ANNOUNCEMENT_FAIL = "UPDATE_ANNOUNCEMENT_FAIL"
export const UPDATE_ANNOUNCEMENT_RESET = "UPDATE_ANNOUNCEMENT_RESET"

export const DELETE_ANNOUNCEMENT_REQUEST = "DELETE_ANNOUNCEMENT_REQUEST"
export const DELETE_ANNOUNCEMENT_SUCCESS = "DELETE_ANNOUNCEMENT_SUCCESS"
export const DELETE_ANNOUNCEMENT_FAIL = "DELETE_ANNOUNCEMENT_FAIL"
export const DELETE_ANNOUNCEMENT_RESET = "DELETE_ANNOUNCEMENT_RESET"

export const NEW_ANNOUNCEMENT_TYPE_REQUEST = "NEW_ANNOUNCEMENT_TYPE_REQUEST"
export const NEW_ANNOUNCEMENT_TYPE_SUCCESS = "NEW_ANNOUNCEMENT_TYPE_SUCCESS"
export const NEW_ANNOUNCEMENT_TYPE_FAIL = "NEW_ANNOUNCEMENT_TYPE_FAIL"
export const NEW_ANNOUNCEMENT_TYPE_RESET = "NEW_ANNOUNCEMENT_TYPE_RESET"

export const DELETE_ANNOUNCEMENT_TYPE_REQUEST = "DELETE_ANNOUNCEMENT_TYPE_REQUEST"
export const DELETE_ANNOUNCEMENT_TYPE_SUCCESS = "DELETE_ANNOUNCEMENT_TYPE_SUCCESS"
export const DELETE_ANNOUNCEMENT_TYPE_FAIL = "DELETE_ANNOUNCEMENT_TYPE_FAIL"
export const DELETE_ANNOUNCEMENT_TYPE_RESET = "DELETE_ANNOUNCEMENT_TYPE_RESET"

export const CLEAR_ERRORS = "CLEAR_ERRORS"