export const ALL_ANNOUNCEMENTS_REQUEST = "ALL_ANNOUNCEMENTS_REQUEST"
export const ALL_ANNOUNCEMENTS_SUCCESS = "ALL_ANNOUNCEMENTS_SUCCESS"
export const ALL_ANNOUNCEMENTS_FAIL = "ALL_ANNOUNCEMENTS_FAIL"

export const ANNOUNCEMENT_DETAILS_REQUEST = "ANNOUNCEMENT_DETAILS_REQUEST"
export const ANNOUNCEMENT_DETAILS_SUCCESS = "ANNOUNCEMENT_DETAILS_SUCCESS"
export const ANNOUNCEMENT_DETAILS_FAIL = "ANNOUNCEMENT_DETAILS_FAIL"

export const ALL_ADMIN_ANNOUNCEMENTS_REQUEST = "ALL_ADMIN_ANNOUNCEMENTS_REQUEST"
export const ALL_ADMIN_ANNOUNCEMENTS_SUCCESS = "ALL_ADMIN_ANNOUNCEMENTS_SUCCESS"
export const ALL_ADMIN_ANNOUNCEMENTS_FAIL = "ALL_ADMIN_ANNOUNCEMENTS_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"