export const ALL_ANNOUNCEMENTS_REQUEST = "ALL_ANNOUNCEMENTS_REQUEST"
export const ALL_ANNOUNCEMENTS_SUCCESS = "ALL_ANNOUNCEMENTS_SUCCESS"
export const ALL_ANNOUNCEMENTS_FAIL = "ALL_ANNOUNCEMENTS_FAIL"

export const GET_SINGLE_ANNOUNCEMENT_REQUEST = "GET_SINGLE_ANNOUNCEMENT_REQUEST"
export const GET_SINGLE_ANNOUNCEMENT_SUCCESS = "GET_SINGLE_ANNOUNCEMENT_SUCCESS"
export const GET_SINGLE_ANNOUNCEMENT_FAIL = "GET_SINGLE_ANNOUNCEMENT_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"