export const GET_AUDIT_REQUEST = "GET_AUDIT_REQUEST"
export const GET_AUDIT_SUCCESS = "GET_AUDIT_SUCCESS"
export const GET_AUDIT_FAIL = "GET_AUDIT_FAIL"

export const NEW_AUDIT_REQUEST = "NEW_AUDIT_REQUEST"
export const NEW_AUDIT_SUCCESS = "NEW_AUDIT_SUCCESS"
export const NEW_AUDIT_FAIL = "NEW_AUDIT_FAIL"
export const NEW_AUDIT_RESET = "NEW_AUDIT_RESET"

export const CLEAR_ERRORS = "CLEAR_ERRORS"