export const ALL_CONVERSATIONS_REQUEST = "ALL_CONVERSATIONS_REQUEST"
export const ALL_CONVERSATIONS_SUCCESS = "ALL_CONVERSATIONS_SUCCESS"
export const ALL_CONVERSATIONS_FAIL = "ALL_CONVERSATIONS_FAIL"

export const BOTH_CONVERSATIONS_REQUEST = "BOTH_CONVERSATIONS_REQUEST"
export const BOTH_CONVERSATIONS_SUCCESS = "BOTH_CONVERSATIONS_SUCCESS"
export const BOTH_CONVERSATIONS_FAIL = "BOTH_CONVERSATIONS_FAIL"

export const CREATE_CONVERSATION_REQUEST = "CREATE_CONVERSATION_REQUEST"
export const CREATE_CONVERSATION_SUCCESS = "CREATE_CONVERSATION_SUCCESS"
export const CREATE_CONVERSATION_FAIL = "CREATE_CONVERSATION_FAIL"
export const CREATE_CONVERSATION_RESET = "CREATE_CONVERSATION_RESET"

export const ALL_MESSAGES_REQUEST = "ALL_MESSAGES_REQUEST"
export const ALL_MESSAGES_SUCCESS = "ALL_MESSAGES_SUCCESS"
export const ALL_MESSAGES_FAIL = "ALL_MESSAGES_FAIL"

export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST"
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS"
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL"
export const SEND_MESSAGE_RESET = "SEND_MESSAGE_RESET"

export const CLEAR_ERRORS = "CLEAR_ERRORS"