export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST"
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS"
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL"
export const SEND_MESSAGE_RESET = "SEND_MESSAGE_RESET"

export const CREATE_CONVERSATION_REQUEST = "CREATE_CONVERSATION_REQUEST"
export const CREATE_CONVERSATION_SUCCESS = "CREATE_CONVERSATION_SUCCESS"
export const CREATE_CONVERSATION_FAIL = "CREATE_CONVERSATION_FAIL"
export const CREATE_CONVERSATION_RESET = "CREATE_CONVERSATION_RESET"

export const GET_CONVERSATIONS_REQUEST = "GET_CONVERSATIONS_REQUEST"
export const GET_CONVERSATIONS_SUCCESS = "GET_CONVERSATIONS_SUCCESS"
export const GET_CONVERSATIONS_FAIL = "GET_CONVERSATIONS_FAIL"

export const GET_BOTH_CONVERSATIONS_REQUEST = "GET_BOTH_CONVERSATIONS_REQUEST"
export const GET_BOTH_CONVERSATIONS_SUCCESS = "GET_BOTH_CONVERSATIONS_SUCCESS"
export const GET_BOTH_CONVERSATIONS_FAIL = "GET_BOTH_CONVERSATIONS_FAIL"

export const GET_MESSAGES_REQUEST = "GET_MESSAGES_REQUEST"
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS"
export const GET_MESSAGES_FAIL = "GET_MESSAGES_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"