export const NEW_FORM_REQUEST = "NEW_FORM_REQUEST"
export const NEW_FORM_SUCCESS = "NEW_FORM_SUCCESS"
export const NEW_FORM_FAIL = "NEW_FORM_FAIL"
export const NEW_FORM_RESET = "NEW_FORM_RESET"

export const ALL_FORMS_REQUEST = "ALL_FORMS_REQUEST"
export const ALL_FORMS_SUCCESS = "ALL_FORMS_SUCCESS"
export const ALL_FORMS_FAIL = "ALL_FORMS_FAIL"

export const FORM_DETAILS_REQUEST = "FORM_DETAILS_REQUEST"
export const FORM_DETAILS_SUCCESS = "FORM_DETAILS_SUCCESS"
export const FORM_DETAILS_FAIL = "FORM_DETAILS_FAIL"

export const UPDATE_FORM_REQUEST = "UPDATE_FORM_REQUEST"
export const UPDATE_FORM_SUCCESS = "UPDATE_FORM_SUCCESS"
export const UPDATE_FORM_FAIL = "UPDATE_FORM_FAIL"
export const UPDATE_FORM_RESET = "UPDATE_FORM_RESET"

export const DELETE_FORM_REQUEST = "DELETE_FORM_REQUEST"
export const DELETE_FORM_SUCCESS = "DELETE_FORM_SUCCESS"
export const DELETE_FORM_FAIL = "DELETE_FORM_FAIL"
export const DELETE_FORM_RESET = "DELETE_FORM_RESET"

export const CLEAR_ERRORS = "CLEAR_ERRORS"