export const REQUEST_DETAILS_REQUEST = "REQUEST_DETAILS_REQUEST"
export const REQUEST_DETAILS_SUCCESS = "REQUEST_DETAILS_SUCCESS"
export const REQUEST_DETAILS_FAIL = "REQUEST_DETAILS_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"