export const REQUEST_DETAILS_REQUEST = "REQUEST_DETAILS_REQUEST"
export const REQUEST_DETAILS_SUCCESS = "REQUEST_DETAILS_SUCCESS"
export const REQUEST_DETAILS_FAIL = "REQUEST_DETAILS_FAIL"
export const REQUEST_DETAILS_RESET = "REQUEST_DETAILS_RESET"

export const SAVE_FORM_REQUEST = "SAVE_FORM_REQUEST"
export const SAVE_FORM_SUCCESS = "SAVE_FORM_SUCCESS"
export const SAVE_FORM_FAIL = "SAVE_FORM_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"